[project]
name = "voice-ai-assistant"
version = "0.1.0"
description = "Voice AI Assistant with push-to-talk functionality using Ollama and pyttsx3"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "piper-tts>=1.3.0",
    "gradio>=5.38.0",
    "numpy>=2.2.6",
    "ollama>=0.5.1",
    "openai-whisper>=20250625",
    "scipy>=1.16.0",
    "sounddevice>=0.5.2",
    "soundfile>=0.12.0",
    "speechrecognition>=3.14.3",
]

[project.scripts]
voice-assistant = "voice_ai_assistant.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
chattts = { git = "https://github.com/2noise/ChatTTS.git" }
